from .services.test_User_register_service import Test_user_register_service
from .services.test_Institution_register_service import test_Institution_register_service
from .services.test_User_delete_service import test_User_delete_service
