#Dev database

version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: upet_dev
      POSTGRES_PASSWORD: upet
      POSTGRES_DB: UPet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
