version: '3.10'

services:
  web:
    build: .
    command: bash -c "cd app && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./UPet-api:/app:ro
    env_file:
      - .env
    networks:
      - internal
    expose:
      - "8000"  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "80:80" 
    depends_on:
      - web
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
