# Generated by Django 5.1.2 on 2024-10-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('data_de_nascimento', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('descricao', models.CharField(max_length=500)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.clusters')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
