# Generated by Django 5.1.2 on 2024-10-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clusters_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
