# Generated by Django 5.1.2 on 2024-10-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Users',
        ),
    ]
