# Generated by Django 5.1.2 on 2024-10-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_usuarios_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusters',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clusters',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='data_de_nascimento',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='telefone',
            new_name='telephone',
        ),
    ]
