# Generated by Django 5.1.2 on 2024-10-30 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_descricao_clusters_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="users",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="core.clusters",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users_picture/"),
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(default="", max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login",
                        to="core.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("species", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=500)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="users_picture/"
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="core.clusters",
                    ),
                ),
            ],
        ),
    ]
