# Generated by Django 5.1.2 on 2024-10-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_institution_users_password_alter_users_cluster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
