# Generated by Django 5.1.2 on 2024-10-30 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_login_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="login",
            name="institution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login",
                to="core.institution",
            ),
        ),
    ]
